image: python:3.10

stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache/

before_script:
  - python --version
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install coverage
  - export PYTHONPATH=$CI_PROJECT_DIR/app/src:$CI_PROJECT_DIR/app

test:
  stage: test
  script:
    - coverage run -m unittest discover -s app/test -p "*.py"
    - coverage report -m
    - coverage html
  artifacts:
    paths:
      - htmlcov
    expire_in: 1 week
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+)%/'
