image: python:3.10

stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache/

before_script:
  - python --version
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install coverage

test:
  stage: test
  script:
    - pwd
    - ls -R $CI_PROJECT_DIR/src
    - export PYTHONPATH=$CI_PROJECT_DIR/src:$CI_PROJECT_DIR/test
    - cp $CI_PROJECT_DIR/app/src/data/users.json $CI_PROJECT_DIR/app/src/data/
    - coverage run -m unittest discover -v -s test -p "*.py"
    - coverage report -m
    - coverage html
  artifacts:
    paths:
      - htmlcov
    expire_in: 1 week
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+)%/'
