image: python:3.10

stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache/

before_script:
  - python --version
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install coverage

test:
  stage: test
  cache:
    paths:
      - .pip-cache/
  script:
    - pwd  # Print current working directory
    - ls -R  # List all files and directories to verify structure
    - export PYTHONPATH="$CI_PROJECT_DIR/src/app:$CI_PROJECT_DIR/test"
    - python -m unittest discover -v -s "$CI_PROJECT_DIR/test" -p "*.py"  # Absolute path
    - coverage run -m unittest discover -v -s "$CI_PROJECT_DIR/test" -p "*.py"  # Absolute path
    - coverage report -m --omit="src/test/*,*/__init__.py"
    - coverage html
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: htmlcov/index.html  # Ensure this path is correct
    paths:
      - htmlcov/
    expire_in: 1 week
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .pip-cache/
