image: python:3.10

stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache/

before_script:
  - python --version
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install coverage

test:
  stage: test
  cache:
    paths:
      - .pip-cache/
  script:
    - export PYTHONPATH=$CI_PROJECT_DIR/src:$CI_PROJECT_DIR/test
    - cd src  # Change to the `src` directory
    - coverage run --omit="test/*" -m unittest test.create_user_test
    - coverage run --append --omit="test/*" -m unittest test.filter_test
    - coverage run --append --omit="test/*" -m unittest test.location_test
    - coverage run --append --omit="test/*" -m unittest test.login_test
    - coverage run --append --omit="test/*" -m unittest test.user_test
    - coverage report
    - coverage xml  # Ensure this command generates `coverage.xml` in the current directory
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: src/coverage.xml
    paths:
      - coverage.xml
      - htmlcov
    expire_in: 1 week
